// <auto-generated />
namespace TrueCrimeRepo.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class dropdownlistwork : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dropdownlistwork));
        
        string IMigrationMetadata.Id
        {
            get { return "202012300454150_dropdown list work"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
